"""empty message

Revision ID: 062c685c9f98
Revises: 94992afa3ca7
Create Date: 2023-02-25 23:23:05.399182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062c685c9f98'
down_revision = '94992afa3ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.drop_column('sims_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sims_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
