"""empty message

Revision ID: 096df32eab43
Revises: 367030a130fd
Create Date: 2023-03-22 00:31:49.722855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096df32eab43'
down_revision = '367030a130fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
