"""empty message

Revision ID: 0d7eeb3ab5fe
Revises: f55fbb792f83
Create Date: 2023-03-07 00:01:52.020793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7eeb3ab5fe'
down_revision = 'f55fbb792f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_object',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'object_id')
    )
    op.drop_table('object_room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_room',
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], name='object_room_object_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='object_room_room_id_fkey')
    )
    op.drop_table('room_object')
    # ### end Alembic commands ###
