"""empty message

Revision ID: 2d7526fac270
Revises: 25c81f4e24f6
Create Date: 2023-02-22 21:10:49.749248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7526fac270'
down_revision = '25c81f4e24f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_pack', sa.String(length=80), nullable=False))
        batch_op.drop_column('age_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('object_pack')

    # ### end Alembic commands ###
