"""empty message

Revision ID: 58f4f00ae9d4
Revises: c32d5c54a554
Create Date: 2023-03-11 00:59:16.670318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f4f00ae9d4'
down_revision = 'c32d5c54a554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=False),
    sa.Column('left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('room_object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_object',
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('top', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], name='room_object_object_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='room_object_room_id_fkey'),
    sa.PrimaryKeyConstraint('room_id', 'object_id', name='room_object_pkey')
    )
    op.drop_table('object_place')
    # ### end Alembic commands ###
