"""empty message

Revision ID: 777504633289
Revises: 58f4f00ae9d4
Create Date: 2023-03-17 00:38:22.959443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777504633289'
down_revision = '58f4f00ae9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
