"""empty message

Revision ID: 7794fb7ad33a
Revises: f2e968499f29
Create Date: 2023-03-02 01:00:09.547538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7794fb7ad33a'
down_revision = 'f2e968499f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint('room_sims_name_key', type_='unique')
        batch_op.drop_column('sims_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sims_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('room_sims_name_key', ['sims_name'])

    # ### end Alembic commands ###
