"""empty message

Revision ID: 8a722ebcd5fa
Revises: 95796715ac87
Create Date: 2023-02-21 01:41:36.779670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a722ebcd5fa'
down_revision = '95796715ac87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('buy_url', sa.String(length=500), nullable=False),
    sa.Column('sims_pic_url', sa.String(length=500), nullable=False),
    sa.Column('real_pic_url', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    with op.batch_alter_table('fav_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fav_room_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('item_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('item_room_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('meta_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('meta_item_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('meta_item_item_id_fkey', 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('item_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('item_room_item_id_fkey', 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('fav_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fav_room_item_id_fkey', 'item', ['item_id'], ['id'])
        batch_op.drop_column('item_id')

    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('buy_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('pic_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.drop_table('item')
    # ### end Alembic commands ###
