"""empty message

Revision ID: 94992afa3ca7
Revises: 2d7526fac270
Create Date: 2023-02-25 21:00:01.835896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94992afa3ca7'
down_revision = '2d7526fac270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
