"""empty message

Revision ID: 95796715ac87
Revises: 2e41404c898e
Create Date: 2023-02-20 01:47:51.372090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95796715ac87'
down_revision = '2e41404c898e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
