"""empty message

Revision ID: 9eceb5400b05
Revises: 972e45644bad
Create Date: 2023-02-27 16:21:30.878974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eceb5400b05'
down_revision = '972e45644bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sims_name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['sims_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sims_name')

    # ### end Alembic commands ###
