"""empty message

Revision ID: ac1252960867
Revises: 
Create Date: 2023-03-01 22:51:57.955928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1252960867'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sims_name', sa.String(length=80), nullable=False),
    sa.Column('buy_url', sa.String(length=2000), nullable=False),
    sa.Column('sims_pic_url', sa.String(length=2000), nullable=False),
    sa.Column('real_pic_url', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sims_name')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sims_name', sa.String(length=80), nullable=False),
    sa.Column('pic_url', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sims_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fav_object',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('object_id', 'user_id')
    )
    op.create_table('fav_room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_table('meta_object',
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ),
    sa.ForeignKeyConstraint(['object_name'], ['object.name'], ),
    sa.PrimaryKeyConstraint('object_name', 'meta_id')
    )
    op.create_table('meta_room',
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ),
    sa.ForeignKeyConstraint(['room_name'], ['room.name'], ),
    sa.PrimaryKeyConstraint('meta_id', 'room_name')
    )
    op.create_table('object_room',
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['object_name'], ['object.name'], ),
    sa.ForeignKeyConstraint(['room_name'], ['room.name'], ),
    sa.PrimaryKeyConstraint('object_name', 'room_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object_room')
    op.drop_table('meta_room')
    op.drop_table('meta_object')
    op.drop_table('fav_room')
    op.drop_table('fav_object')
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('object')
    op.drop_table('meta')
    # ### end Alembic commands ###
