"""empty message

Revision ID: c32d5c54a554
Revises: 0d7eeb3ab5fe
Create Date: 2023-03-11 00:49:30.652846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32d5c54a554'
down_revision = '0d7eeb3ab5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('left', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_object', schema=None) as batch_op:
        batch_op.drop_column('left')
        batch_op.drop_column('top')

    # ### end Alembic commands ###
