"""empty message

Revision ID: d167bf5d54de
Revises: 746bbac5e276
Create Date: 2023-03-03 23:20:18.763319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd167bf5d54de'
down_revision = '746bbac5e276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('meta_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('meta_object_meta_description_fkey', type_='foreignkey')
        batch_op.drop_constraint('meta_object_object_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'meta', ['meta_id'], ['id'])
        batch_op.create_foreign_key(None, 'object', ['object_id'], ['id'])
        batch_op.drop_column('object_name')
        batch_op.drop_column('meta_description')

    with op.batch_alter_table('meta_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('meta_room_meta_description_fkey', type_='foreignkey')
        batch_op.drop_constraint('meta_room_room_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'room', ['room_id'], ['id'])
        batch_op.create_foreign_key(None, 'meta', ['meta_id'], ['id'])
        batch_op.drop_column('meta_description')
        batch_op.drop_column('room_name')

    with op.batch_alter_table('object_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('object_room_object_name_fkey', type_='foreignkey')
        batch_op.drop_constraint('object_room_room_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'room', ['room_id'], ['id'])
        batch_op.create_foreign_key(None, 'object', ['object_id'], ['id'])
        batch_op.drop_column('object_name')
        batch_op.drop_column('room_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('object_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('object_room_room_name_fkey', 'room', ['room_name'], ['name'])
        batch_op.create_foreign_key('object_room_object_name_fkey', 'object', ['object_name'], ['name'])
        batch_op.drop_column('object_id')
        batch_op.drop_column('room_id')

    with op.batch_alter_table('meta_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('meta_room_room_name_fkey', 'room', ['room_name'], ['name'])
        batch_op.create_foreign_key('meta_room_meta_description_fkey', 'meta', ['meta_description'], ['description'])
        batch_op.drop_column('room_id')
        batch_op.drop_column('meta_id')

    with op.batch_alter_table('meta_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('object_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('meta_object_object_name_fkey', 'object', ['object_name'], ['name'])
        batch_op.create_foreign_key('meta_object_meta_description_fkey', 'meta', ['meta_description'], ['description'])
        batch_op.drop_column('meta_id')
        batch_op.drop_column('object_id')

    # ### end Alembic commands ###
