"""empty message

Revision ID: f2e968499f29
Revises: ac1252960867
Create Date: 2023-03-01 23:13:20.244780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e968499f29'
down_revision = 'ac1252960867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=True))
        batch_op.drop_column('style')
        batch_op.drop_column('type')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('style', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
