"""empty message

Revision ID: f55fbb792f83
Revises: d167bf5d54de
Create Date: 2023-03-04 00:01:52.215083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55fbb792f83'
down_revision = 'd167bf5d54de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=80), nullable=True))
        batch_op.drop_constraint('meta_description_key', type_='unique')
        batch_op.create_unique_constraint(None, ['tag'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('meta_description_key', ['description'])
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
