"""empty message

Revision ID: feb76eda2beb
Revises: 9eceb5400b05
Create Date: 2023-02-28 15:17:23.863085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb76eda2beb'
down_revision = '9eceb5400b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sims_name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['sims_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sims_name')

    # ### end Alembic commands ###
